#!/usr/bin/env bash
# Compile the core and REPORT THE TIMING, not just the exit code.
#
#     scripts/build.sh            # full compile
#     scripts/build.sh --map      # analysis & synthesis only (fast syntax check)
#     scripts/build.sh --report   # re-read the last build's reports, compile nothing
#
# The reason this exists rather than a bare `quartus_sh --flow compile`:
# Quartus reports "Fitter was successful" on a design that grossly fails
# timing, and nothing in the default flow warns you. Seta.sdc's own header
# says to always read output_files/<rev>.sta.summary afterwards -- so read it
# here, every time, and make a timing failure as loud as a syntax error.
set -euo pipefail

[ -d sys ] || { echo "run me from the repository root"; exit 1; }

# TOOL PATH RESOLUTION.
#
# Probed rather than asserted, because "bash" on this machine is ambiguous:
# PATH also contains WSL's bash, which is a different OS with /mnt/c instead of
# /c and cannot run Windows .exe tools at all. A Python wrapper that spawns
# plain `bash` gets THAT one, so a script passes when you run it by hand and
# fails from the wrapper, reporting "No such file or directory" for a path that
# plainly exists. scripts/maincpu_sweep.py now names the Git bash explicitly;
# this probe is the second line of defence, and covers a machine where the
# tools simply live elsewhere.
Q=""
for _c in "${QUARTUS_BIN:-}"           /c/intelFPGA_lite/17.0/quartus/bin64           C:/intelFPGA_lite/17.0/quartus/bin64 ; do
	[ -n "$_c" ] && [ -x "$_c/quartus_sh.exe" ] && Q="$_c" && break
done
[ -n "$Q" ] || { echo "Quartus not found. Set QUARTUS_BIN."; exit 1; }
REV=Seta
OUT=output_files

mode="${1:-full}"

if [ "$mode" != "--report" ]; then
	mkdir -p "$OUT"
	# build_id.v is generated by the PRE_FLOW script, which only runs for a
	# real flow. quartus_map on its own does not trigger it, and the missing
	# file reads as a confusing `can't open Verilog Design File` in Seta.sv.
	"$Q/quartus_sh.exe" -t sys/build_id.tcl x "$REV" "$REV" >/dev/null

	if [ "$mode" = "--map" ]; then
		"$Q/quartus_map.exe" --read_settings_files=on --write_settings_files=off \
			"$REV" -c "$REV" 2>&1 | tee "$OUT/build.log" | grep -E "^Error|^\s+Error" || true
		grep -qE "^Error" "$OUT/build.log" && { echo "SYNTHESIS FAILED"; exit 1; }
		echo "analysis & synthesis OK"
		exit 0
	fi

	"$Q/quartus_sh.exe" --flow compile "$REV" -c "$REV" > "$OUT/build.log" 2>&1 || {
		echo "COMPILE FAILED"; grep -E "^Error|^\s+Error" "$OUT/build.log" | head -20; exit 1; }
fi

echo
echo "==== resource usage ===================================================="
# .fit.summary is a plain "key : value" list with no "Fitter Summary" banner --
# an earlier sed range keyed on one matched nothing and printed an empty
# section, which looks the same as a build with no resources to report.
grep -E "Logic utilization|Total registers|Total block memory bits|Total RAM Blocks|Total DSP Blocks|Total pins|Total PLLs" \
	"$OUT/$REV.fit.summary" || echo "(no $OUT/$REV.fit.summary)"

echo
echo "==== timing ============================================================"
if [ -f "$OUT/$REV.sta.summary" ]; then
	cat "$OUT/$REV.sta.summary"
else
	echo "no $OUT/$REV.sta.summary -- STA did not run"
	exit 1
fi

# A negative slack anywhere is a failure, whatever the fitter said. Scan the
# summary rather than trusting the flow's exit code.
if grep -qE "Slack[[:space:]]*:[[:space:]]*-" "$OUT/$REV.sta.summary"; then
	echo
	echo "*** TIMING NOT MET -- negative slack above. The .rbf is not trustworthy. ***"
	exit 1
fi

echo
if [ -f "$OUT/$REV.rbf" ]; then
	ls -l "$OUT/$REV.rbf"
	echo "timing met."
else
	echo "no .rbf produced"
	exit 1
fi
